"""Project-wide logging facade.

Stdlib `logging`, two sinks:

  * console  — INFO+ to stderr, single-line format
  * file     — DEBUG+ to ``logs/{run_id}.log``, rotating, full timestamp

Libraries (engine/, drivers/, models/, cube/) never configure handlers
themselves — they just do `log = get_logger(__name__)` and call
`log.info(...)`. The application (a script, notebook, or main()) calls
`configure(...)` once at startup. This matches the standard Python
guideline that library code attaches to loggers and applications
configure them.

Every `configure()` returns a `RunContext` carrying a fresh ``run_id``
(UTC timestamp, optional suffix). Consumers — like `PipelineRunner` —
use that id to name their RunResult JSON dump.

Usage
-----
    # In a top-level script
    from engine.log import configure
    ctx = configure(level="INFO", log_dir="logs")
    print(f"run_id = {ctx.run_id}; tail logs/{ctx.run_id}.log")

    # In any library module
    from engine.log import get_logger
    log = get_logger(__name__)
    log.info("starting fetch for variable %s", name)
    log.debug("verbose detail only in the file log")

Why a tiny wrapper instead of bare `logging`:

  * Centralises the "logs/" file path convention.
  * Gives the runner a stable `run_id` to label both stdout and JSON.
  * Lets us swap in structured logging (JSONFormatter) later without
    touching every call site.
"""
from __future__ import annotations

import logging
import logging.handlers
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Union


_DEFAULT_FMT = "%(asctime)s %(levelname)-7s %(name)s: %(message)s"
_DEFAULT_DATEFMT = "%Y-%m-%d %H:%M:%S"

_PROJECT_ROOT_LOGGER = "nasa_project"


@dataclass(frozen=True)
class RunContext:
    """Identifies one configured run. Used to label log files + JSON dumps."""
    run_id: str
    log_dir: Path
    log_file: Optional[Path]


def get_logger(name: str) -> logging.Logger:
    """Return the module logger. Safe to call before configure()."""
    if name and name != _PROJECT_ROOT_LOGGER and \
            not name.startswith(_PROJECT_ROOT_LOGGER + "."):
        # Map module names (engine.scheduler, drivers.era5_wind, ...) into
        # a single project sub-tree so a sysadmin can silence the whole
        # project with one logger.setLevel call.
        name = f"{_PROJECT_ROOT_LOGGER}.{name}"
    return logging.getLogger(name)


def configure(
    *,
    level: Union[int, str] = "INFO",
    file_level: Union[int, str] = "DEBUG",
    log_dir: Union[str, Path] = "logs",
    run_id: Optional[str] = None,
    label: Optional[str] = None,
    quiet: bool = False,
    max_bytes: int = 10 * 1024 * 1024,
    backup_count: int = 5,
) -> RunContext:
    """Configure the project's root logger. Idempotent (safe to call twice).

    Parameters
    ----------
    level : console handler threshold (default INFO).
    file_level : file handler threshold (default DEBUG).
    log_dir : where to write the rotating file log.
    run_id : override the autogenerated UTC timestamp run id.
    label : optional short tag glued onto run_id (e.g. ``dallas_2025``).
    quiet : suppress the console handler (file-only).
    max_bytes / backup_count : passed to ``RotatingFileHandler``.

    Returns
    -------
    RunContext with the resolved ``run_id`` and the log file path.
    """
    root = logging.getLogger(_PROJECT_ROOT_LOGGER)
    # Stop log records from propagating up to the root logger (which
    # libraries like xarray/zarr touch with their own handlers).
    root.propagate = False

    # Wipe handlers from any previous call so configure() is idempotent.
    for h in list(root.handlers):
        root.removeHandler(h)

    rid = run_id or _make_run_id(label)
    log_dir_path = Path(log_dir)
    log_dir_path.mkdir(parents=True, exist_ok=True)

    formatter = logging.Formatter(_DEFAULT_FMT, _DEFAULT_DATEFMT)

    log_file: Optional[Path] = None
    if max_bytes > 0:
        log_file = log_dir_path / f"{rid}.log"
        fh = logging.handlers.RotatingFileHandler(
            log_file, maxBytes=max_bytes,
            backupCount=backup_count, encoding="utf-8")
        fh.setLevel(_coerce_level(file_level))
        fh.setFormatter(formatter)
        root.addHandler(fh)

    if not quiet:
        ch = logging.StreamHandler(sys.stderr)
        ch.setLevel(_coerce_level(level))
        ch.setFormatter(formatter)
        root.addHandler(ch)

    # Effective root level = min(handler thresholds) so records reach
    # both sinks.
    root.setLevel(min(
        _coerce_level(level),
        _coerce_level(file_level) if log_file is not None else _coerce_level(level)))

    return RunContext(run_id=rid, log_dir=log_dir_path, log_file=log_file)


def _make_run_id(label: Optional[str]) -> str:
    """UTC timestamp run id; appended label cannot contain path separators."""
    base = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    if not label:
        return base
    safe = "".join(c if c.isalnum() or c in "-_." else "_"
                    for c in label)
    return f"{base}_{safe}"


def _coerce_level(level: Union[int, str]) -> int:
    if isinstance(level, int):
        return level
    return getattr(logging, str(level).upper())
