"""Stage-4 explicit semantic transformation layer."""

from .model import (
    TransformationCatalog,
    TransformationKind,
    TransformationLossPolicy,
    TransformationPort,
    TransformationSpec,
    UncertaintyPropagationPolicy,
    UnitAffineRule,
    ValueSemantics,
    exact_requirement,
    unit_affine_rule,
    unit_affine_rules,
    verify_bound_transformation_authority,
    verify_capability_transformation_authority,
)
from .search import (
    ReachableDescriptorState,
    TransformationExpansion,
    TransformationDiscoveryReplay,
    TransformationFrontierCode,
    TransformationFrontierItem,
    TransformationLimitCode,
    TransformationLimitReason,
    TransformationSearchLimits,
    TransformationTransition,
    expand_transform_catalog,
)

__all__ = [
    "ReachableDescriptorState",
    "TransformationCatalog",
    "TransformationExpansion",
    "TransformationDiscoveryReplay",
    "TransformationFrontierCode",
    "TransformationFrontierItem",
    "TransformationKind",
    "TransformationLossPolicy",
    "TransformationLimitCode",
    "TransformationLimitReason",
    "TransformationPort",
    "TransformationSearchLimits",
    "TransformationSpec",
    "TransformationTransition",
    "UncertaintyPropagationPolicy",
    "UnitAffineRule",
    "ValueSemantics",
    "exact_requirement",
    "expand_transform_catalog",
    "unit_affine_rule",
    "unit_affine_rules",
    "verify_bound_transformation_authority",
    "verify_capability_transformation_authority",
]
