"""Stage-2 typed scientific contracts and direct compatibility proofs."""
from .evidence import (
    BoundKind,
    EvidenceApplicability,
    EvidenceClaim,
    EstimateUncertainty,
    EvidenceProfile,
    EvidenceSnapshot,
    EvidenceStatus,
    EvidenceSubject,
    MetricComposition,
    MetricDefinition,
    MetricEvaluator,
)
from .identity import (
    ScientificIdentity,
    canonical_crs,
    canonical_decimal,
    canonical_timestamp,
    canonical_unit,
)
from .matching import (
    CheckStatus,
    CompatibilityCheck,
    CompatibilityProof,
    MatchCode,
    direct_match,
)
from .requirements import (
    CadencePolicy,
    Cardinality,
    CardinalityKind,
    ConstraintMode,
    DistinctnessPolicy,
    EvidenceBound,
    EvidenceRequirement,
    MissingPolicy,
    Requirement,
    RequirementUse,
    SpatialRequirement,
    TemporalRequirement,
    UnknownPolicy,
    ValueConstraint,
    VerticalRequirement,
)
from .types import (
    ArtifactDescriptor,
    BBoxSupport,
    GridDescriptor,
    IntrinsicUncertainty,
    Missingness,
    MissingnessStatus,
    OriginClass,
    SampleSemantics,
    ScaleBasis,
    SpatialScale,
    TemporalKind,
    TemporalSupport,
    UncertaintyStatus,
    VerticalKind,
    VerticalSupport,
)

__all__ = [
    "ArtifactDescriptor", "BBoxSupport", "BoundKind", "CadencePolicy",
    "Cardinality", "CardinalityKind", "CheckStatus", "CompatibilityCheck",
    "CompatibilityProof", "ConstraintMode", "DistinctnessPolicy",
    "EvidenceApplicability", "EvidenceBound", "EvidenceClaim",
    "EstimateUncertainty",
    "EvidenceProfile", "EvidenceRequirement", "EvidenceSnapshot",
    "EvidenceStatus", "EvidenceSubject", "GridDescriptor",
    "IntrinsicUncertainty", "MatchCode",
    "MetricComposition", "MetricDefinition", "MetricEvaluator",
    "MissingPolicy", "Missingness", "MissingnessStatus", "OriginClass",
    "Requirement", "RequirementUse", "SampleSemantics", "ScaleBasis",
    "ScientificIdentity", "SpatialRequirement", "SpatialScale",
    "TemporalKind", "TemporalRequirement", "TemporalSupport",
    "UncertaintyStatus", "UnknownPolicy",
    "ValueConstraint", "VerticalKind", "VerticalRequirement", "VerticalSupport",
    "canonical_crs", "canonical_decimal", "canonical_timestamp",
    "canonical_unit", "direct_match",
]
