"""Stage-3 recursive workflow resolution and exact global selection."""

from .benchmark import PlanningBenchmarkProfile

from .hypergraph import (
    ArtifactAvailabilitySnapshot,
    ArtifactCommitRecord,
    ArtifactCommitStatus,
    BackReference,
    BackReferenceKind,
    DiscoveryLimitCode,
    DiscoveryLimitReason,
    DiscoveryLimits,
    DiscoveryRejection,
    DiscoveryTimings,
    FeasibleDerivationHypergraph,
    FeasibleHypergraph,
    HypergraphBuilder,
    build_feasible_hypergraph,
)
from .milp import (
    DeploymentOption,
    MilpSelectionProblem,
    MilpSelectionResult,
    MilpSolveOptions,
    MilpStatus,
    ProducerSelectionRef,
    SatisfactionArcSelectionRef,
    SelectionConstraints,
    solve_milp,
)
from .projection import project_oracle_problem
from .service import (
    PlanningMetrics,
    ResolutionOutcome,
    ResolutionStatus,
    WorkflowResolver,
)
from .upstream import (
    DiscoveryCertificate,
    DiscoveryLayerCertificate,
    DiscoveryLayerScope,
    DiscoveryLimitActivation,
    DiscoveryLimitSetting,
    DiscoveryUniverseContract,
    UpstreamCompleteness,
)
from .validator import (
    ArtifactCommitAttestation,
    ProofReplayContext,
    SelectedPlanValidationReport,
    ValidationBlocker,
    ValidationBlockerTree,
    ValidationCode,
    validate_selected_plan,
)

__all__ = [
    "ArtifactAvailabilitySnapshot",
    "ArtifactCommitAttestation",
    "ArtifactCommitRecord",
    "ArtifactCommitStatus",
    "BackReference",
    "BackReferenceKind",
    "DeploymentOption",
    "DiscoveryCertificate",
    "DiscoveryLayerCertificate",
    "DiscoveryLayerScope",
    "DiscoveryLimitCode",
    "DiscoveryLimitActivation",
    "DiscoveryLimitReason",
    "DiscoveryLimitSetting",
    "DiscoveryUniverseContract",
    "DiscoveryLimits",
    "DiscoveryRejection",
    "DiscoveryTimings",
    "FeasibleDerivationHypergraph",
    "FeasibleHypergraph",
    "HypergraphBuilder",
    "MilpSelectionProblem",
    "MilpSelectionResult",
    "MilpSolveOptions",
    "MilpStatus",
    "PlanningMetrics",
    "PlanningBenchmarkProfile",
    "ProducerSelectionRef",
    "SatisfactionArcSelectionRef",
    "ProofReplayContext",
    "ResolutionOutcome",
    "ResolutionStatus",
    "SelectedPlanValidationReport",
    "SelectionConstraints",
    "UpstreamCompleteness",
    "ValidationBlocker",
    "ValidationBlockerTree",
    "ValidationCode",
    "WorkflowResolver",
    "build_feasible_hypergraph",
    "project_oracle_problem",
    "solve_milp",
    "validate_selected_plan",
]
